### ISSUE TITLE
Add OpenShift tutorial

### ISSUE THREAD

**Issue by moabu** [GluuFederation/cloud-native-edition#188]

**Comment by moabu** [comment]
## Initial doc to be submitted after thorough testing on all platforms.


Example setup on Google cloud platform: 

1. Install OCP4.5.7 

1. Enable the following API Services needed by the cluster
    
    ```
    Compute Engine API (compute.googleapis.com)
    Google Cloud APIs (cloudapis.googleapis.com)
    Cloud Resource Manager API (cloudresourcemanager.googleapis.com)
    Google DNS API (dns.googleapis.com)
    Identity and Access Management (IAM) API (iam.googleapis.com)
    IAM Service Account Credentials API (iamcredentials.googleapis.com)
    Service Management API (servicemanagement.googleapis.com)
    Service Usage API (serviceusage.googleapis.com)
    Google Cloud Storage JSON API (storage-api.googleapis.com)
    Cloud Storage (storage-component.googleapis.com)
    ```

1. Setup DNS
    - Create Public Zone
    - Get Public Nameservers of the DNS Zone

1. Create Installer Service Account and set it inside your environment. 

    ```
    GOOGLE_APPLICATION_CREDENTIALS=path/to/your/service_account_key_file.json
    ````

1. Install Cluster with the OpenShift Installer

    ```
    openshift-install create install-config --dir=path/to/dir/
    ```
    ```
    vi path/to/dir/install-config.yaml
    apiVersion: v1
    baseDomain: gluuatopenshift.liber-apps.com
    compute:
    - architecture: amd64
      hyperthreading: Enabled
      name: worker
      platform:
        gcp:
	       type: e2-highcpu-8 
           zones:
           - us-west1-a
           - us-west1-c
      replicas: 3
    controlPlane:
      architecture: amd64
      hyperthreading: Enabled
      name: master
      platform:
        gcp:
	        type: e2-highcpu-8 
            zones:
            - us-west1-a
            - us-west1-c
      replicas: 3
    metadata:
      creationTimestamp: null
      name: opc4
    networking:
      clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      machineNetwork:
      - cidr: 10.0.0.0/16
      networkType: OpenShiftSDN
      serviceNetwork:
      - 172.30.0.0/16
    platform:
      gcp:
        projectID: ocp4-gluu
        region: us-west1
    publish: External
    ```

    ```
    openshift-install create cluster --dir=/path/to/dir/ \
    --log-level=debug
    ```

1. To interact with the OCP cluster from the host:

    ```
    mkdir -p $HOME/.kube
    sudo cp -i /path/to/dir/auth/kubeconfig $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config
    ```

    export KUBECONFIG=/path/to/dir/auth/kubeconfig - is only valid for the current session

1. Create user account
    ```
    oc create user <user_name>
    ```

1. To obtain a list of OpenShift users

    ```
    oc get users
    ```

1. To designate some user as administrator

    ```
    kubectl create clusterrolebinding permissive-binding --clusterrole=cluster-admin --user=<user_name> --group=system:serviceaccounts
    ```

1. Configuring an HTPasswd identity provider

    ```
    sudo apt install apache2-utils
    htpasswd -c -B -b <\path\to\users.htpasswd> <user_name> <password>
    oc create secret generic htpass-secret --from-file=htpasswd=</path/to/users.htpasswd> -n openshift-config
    ```
    ```
    vi HTPasswd.yaml
    apiVersion: config.openshift.io/v1
    kind: OAuth
    metadata:
      name: cluster
    spec:
      identityProviders:
      - name: my_htpasswd_provider
        mappingMethod: claim
        type: HTPasswd
        htpasswd:
          fileData:
            name: htpass-secret
    ```

    ```    
    oc apply -f </path/to/CR>
    ```

    ```
    oc login -u <user_name>
    oc whoami
    ```

1. Creating a new service account named useroot

    ```
    oc create serviceaccount useroot
    oc adm policy add-scc-to-user anyuid -z useroot
    ```

1. Install a OpenEBS (1.5 version)

    ```
    oc adm policy add-scc-to-user privileged system:serviceaccount:openebs:openebs-maya-operator #Add OpenEBS Service account to the privileged SCC of OpenShift.
    wget https://openebs.github.io/charts/openebs-operator-1.5.0.yaml
    kubectl apply -f openebs-operator-1.5.0.yaml
    ```
1. For provisioning OpenEBS volumes, you have to edit SCC to allow HostPath volumes and Privileged containers.

    ```
    oc adm policy add-scc-to-user privileged system:serviceaccount:openebs:useroot #oc adm policy add-scc-to-user privileged system:serviceaccount:<project>:<serviceaccountname>
    ```

1. Enable Container Images that Require Root

    ```
    oc adm policy add-scc-to-user anyuid system:serviceaccount:openebs:useroot
    ```

1. Change permissions to dir that contains pygluu-kubernetes.pyz

    ```
    sudo chgrp -R 0 /path/to/dir/ && \
    chmod -R g=u /path/to/dir/
    ```
1. Install the Gluu server:

    ```
    cd /path/to/dir/
    ./pygluu-kubernetes.pyz helm-install
    ```

1. If the nginx-ingress did't work correctly - modifying the deployment configuration for nginx-ingress and then adding the serviceaccount to the anyuid SCC as the application defined needs to run as user root in the container.

    ```
    oc patch deployment.apps/ningress-nginx-ingress-controller --patch '{"spec":{"template":{"spec":{"serviceAccountName": "useroot"}}}}'
    oc patch deployment.apps/ningress-nginx-ingress-default-backend --patch '{"spec":{"template":{"spec":{"serviceAccountName": "useroot"}}}}'
    ```

1. Uninistall OCP4
    
    ```
    openshift-install destroy cluster --dir=<installation_directory> \
    --log-level=debug
    ```

**Comment by Cookedjc** [comment]
Will there be differences for newer OpenShift?  they are now at 4.6 4.7

**Comment by moabu** [comment]
No it should be the same. This is also labeled as a draft.

**Comment by scott45** [comment]
## Setting up Gluu server 4.(2/3) with Openshift (OCP-4.7) on Google Cloud Platform from scratch. (Same should work for most recent OCP-4 4.xx versions)

### Requirements

```
Google Cloud billable account
gcloud cli 
openshift cli tools
pull secret
dns domain (bought from google or delegated to google)
```


1.a  Go to [https://www.openshift.com/try](https://www.openshift.com/try) and Login with your credentials or create a new account, then login. 

b.  Select `cloud`, and scroll down to the `Run it yourself` section. 

c.  Go to `Google Cloud` and select `User provisioned infrastructure`. 

d.  Download the following from that page. (will ask for a directory for the installation program. Using `./ocp4` in this tutorial). First create the directory in a path you can easily access. Create the directory with the following command then save installation files below in it. 

```
mkdir $HOME/Desktop/ocp4
```

- `Openshift installer` for your OS. Currently only Linux and MacOS are supported. Note the directory where you'll store your configuration files. In our case we're using the directory we created above. 

- Download and copy the `pull secret`. You'll be prompted for this during installation. Copy it somewhere and keep it safe. 

- Download the `command line tools`. After completion, there will also be an `oc cli kubeconfig` file downloaded for you.


2.a  Download and install the `gcloud-cli`. Go [here](https://cloud.google.com/sdk/docs) and get the installer for your OS. 

b.  After installing gcloud, Initialise login and authorise gcloud for your account in the browser. Run

```
gcloud init 
```

c.  Go to the [google cloud console](https://console.cloud.google.com) and login to access the cloud console. Ensure you have a billing account associated with it. 

d.  Create a GCP `project` if you don't have any. You can create a project with this command on the terminal

```
gcloud projects create ${gcp_project}
```

e.  Set the region, zone, project etc using
```
gcloud config set project ${gcp_project}
```

f. Verify your configuration values. Run 
```
gcloud config list
```

g.  Enable the following google api's in the UI for your installation to run. Go to the google cloud console, click on navigation menu > API & Services.

```
Compute Engine API -->  (compute.googleapis.com)

Google Cloud APIs -->  (cloudapis.googleapis.com)     

Cloud Resource Manager API --> (cloudresourcemanager.googleapis.com)         

Google DNS API -->   (dns.googleapis.com)

Identity and Access Management (IAM) API --> (iam.googleapis.com)

IAM ServiceAccount Credentials --> (iamcredentials.googleapis.com) 

Identity and Access Management (IAM) API --> (iam.googleapis.com)

Service Management API --> (servicemanagement.googleapis.com)

Service Usage API --> (serviceusage.googleapis.com)                      

Google Cloud Storage JSON API → (storage-api.googleapis.com)           

Cloud Storage --> (storage-component.googleapis.com)
```

**Comment by scott45** [comment]
### (Draft) 

## Setting up Gluu server 4.(2/3) with Openshift (OCP-4.7) on AWS from scratch. (works for recent OCP 4.xx versions)

Requirements
```
AWS account
Use key-based, long-lived credentials. To generate appropriate keys, see [Managing Access Keys for IAM Users](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html)
```

#### 1. Configure route 53
- The `Route 53 service` provides cluster DNS resolution and name lookup for external connections to the cluster
- must have a dedicated public hosted zone in your Route 53 service
- This zone must be authoritative for the domain

b. Have an appropriate `domain` (e.g openshiftcorp.com), `subdomain` (e.g clusters.openshiftcorp.com) and `registrar`. E.g  You can transfer an existing domain or registrar or obtain a new one through AWS

c. If it's an existing domain and registrar, migrate it's `DNS to AWS`. [This link](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/MigratingDNS.html) shows how to do it. 

d. [Create](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/CreatingHostedZone.html) a `public hosted zone` for your domain or subdomain

e. [Extract](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/GetInfoAboutHostedZone.html) the new authoritative name servers from the hosted zone records

f. [Update](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-name-servers-glue-records.html#domain-name-servers-glue-records-procedure) the registrar records for the AWS Route 53 name servers that your domain uses

g. If you are using a subdomain, [add](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/CreatingNewSubdomain.html) its delegation records to the parent domain. This gives Amazon Route 53 responsibility for the subdomain.

h. Configure Ingress Operator endpoint for AWS Route 53. E.g if installing in either Amazon Web Services (AWS) `GovCloud (US) US-West` or `US-East region`, the Ingress Operator uses us-gov-west-1 region for Route53 and tagging API clients. E.g  `https://tagging.us-gov-west-1.amazonaws.com` as the tagging API endpoint.

#### 2. AWS Accounts limits. 

b. OCP4 uses a number of AWS components and the [default service](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) limits might not be enough for the installation. 

If you want to deploy your cluster in certain regions, you might need to request additional resources for your AWS account. 

c. Some of the AWS components whose limits affect installation include the following.
```
Instance Limits
Elastic IPs (EIPs)
Virtual Private Clouds (VPCs
Elastic Load Balancing (ELB/NLB)
NAT Gateways
Elastic Network Interfaces (ENIs)
VPC Gateway
S3 buckets
Security Groups
```

#### 3. Required AWS permissions for the IAM user

b. Attaching the `AdministratorAccess policy` to the `IAM user` that you create in Amazon Web Services (AWS) grants that user all of the required permissions.

c. To deploy all components of an OpenShift Container Platform cluster, the IAM user requires the following permissions:

```
EC2 
Network resources
Elastic Load Balancing 
IAM
Route 53
S3
S3 permissions that cluster Operators require
Required permissions to delete base cluster resources
Required permissions to delete network resources
Additional IAM and S3 permissions that are required to create manifests
Optional permissions for instance and quota checks
```

#### 4. Creating an IAM user

b. Before you install OpenShift Container Platform, [create](Creating an IAM User in Your AWS Account) a secondary `IAM administrative user`.

c. Set the following options as you create the user
- Specify the IAM user name and select `Programmatic access`
- Attach the `AdministratorAccess policy` to ensure that the account has sufficient permission to create the cluster.
- Optional: Add `metadata` to the user by attaching `tags`.
- Confirm that the `user name` that you specified is granted the `AdministratorAccess policy`.
- Record / store / save the `access key ID` and `secret access key` values for local machine configuration.

#### 5. Required AWS permissions for IAM roles

b. You can define your own cloud `identity and access management (IAM)` roles that are applied to the instance profiles of your machines created by the installation program

c. You can specify existing IAM roles by defining the `controlPlane.platform.aws.iamRole` and `compute.platform.aws.iamRoleThis` fields in the `install-config.yaml` file.

#### 6. Supported AWS regions

- Multiple regions are supported in different parts of the continent. We shall be using `us-west-1` in this tutorial. 

The following AWS GovCloud regions are supported `us-gov-west-1` and `us-gov-east-1`

#### 7. Installing the cluster

a. Have a good and stable internet connection. 

b. If you use a firewall, you must [configure it to allow the sites](https://docs.openshift.com/container-platform/4.7/installing/install_config/configuring-firewall.html#configuring-firewall) that your cluster requires access to.

c. [Manually](https://docs.openshift.com/container-platform/4.7/installing/installing_aws/manually-creating-iam.html#manually-creating-iam-aws) create and maintain IAM credentials If you do not allow the system to manage identity and access management (IAM)

d. Generate ssh keys if you didn't have one. They'll be added to the agennt to perform installation debugging or disaster recovery on your cluster

e. Create a cluster to store installation files. We shall be using ocp4 in this tutorial.
```
mkdir ocp4 && cd ocp4
```

f. Access the [Infrastructure Provider page](https://cloud.redhat.com/openshift/install) on the Red Hat OpenShift Cluster Manager site. Login with your credentials or create a new account if you hadn't. 

- Select `cloud`, and scroll down to the `Run it yourself` section.

- Go to `AWS` and select `User provisioned infrastructure`.

- Download the following. 
```
Openshift installer for your OS. Currently only Linux and MacOS are supported. Note that ocp4 directory where you'll store your installation files.

Download and copy the pull secret. You'll be prompted for this during installation. Copy it somewhere and keep it safe.

command line tools containing an oc cli kubeconfig file.
```

- Extract the instllation program

f.  Create install-config file for customising our cluster.
```
./openshift-install create install-config --dir=ocp4
```

At the prompt, you'll provide the following;
- SSH key
- AWS as the platform to target
- AWS access key and secret access key
- Base domain for the Route 53 service
- Cluster name
- Pull secret you obtained in the previous step


g. Open the content of the file with your favourite text editor and modify what you need to.
```
vi ./install-config.yaml

apiVersion: v1
baseDomain: example.com 
credentialsMode: Mint 
controlPlane:   
  hyperthreading: Enabled 
  name: master
  platform:
    aws:
      zones:
      - us-west-2a
      - us-west-2b
      rootVolume:
        iops: 4000
        size: 500
        type: io1 
      type: m5.xlarge
  replicas: 3
compute: 
- hyperthreading: Enabled 
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 500
        type: io1 
      type: c5.4xlarge
      zones:
      - us-west-2c
  replicas: 3
metadata:
  name: test-cluster 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-west-2 
    userTags:
      adminContact: jdoe
      costCenter: 7536
    amiID: ami-96c6f8f7 
    serviceEndpoints: 
      - name: ec2
        url: https://vpce-id.ec2.us-west-2.vpce.amazonaws.com
fips: false 
sshKey: ssh-ed25519 AAAA... 
pullSecret: '{"auths": ...}' 
```

h. Backup the `install-config.yaml` for re-use purpose if you will need to since it is consumed during the installation process.

i. Initialize the cluster deployment. Cluster creation will take about 30 minutes.
```
./openshift-install create cluster --dir=ocp4 --log-level=info 
```

j. Logging in to the cluster by using the web console

- Credentials and url are presented in the terminal after successful creation of the cluster. They can also be accessed in the log file in the current folde
```
vi ./ocp4/.openshift_install.log
```


k. Logging in to the cluster by using the CLI

- Export the kubeadmin credentials
```
export KUBECONFIG=<installation_directory>/auth/kubeconfig 
```

-  Verify you can run oc commands successfully using the exported configuration
```
oc whoami
```
