### ISSUE TITLE
Add method of migration from CE to CN Kubernetes

### ISSUE THREAD

**Issue by moabu** [GluuFederation/cloud-native-edition#24]
We need to detect  all areas of change and migrate connections to CN. 

@nynymike 
IP addresses: in chroot, oxauth connects to LDAP via localhost, so bootstrap LDAP connection properties will need to be updated when migrating to kubernetes. Also, the IP Address is in the chroot httpd.conf Listen directive

Cache Refresh… which uses the file system to store snapshots

Private key access

Is the chroot one instance, or a clustered deployment (using Cluster Manager)?

https://github.com/GluuFederation/enterprise-edition/wiki/chroot-to-kubernetes-migration

**Comment by moabu** [comment]
## Steps

1.  Prepare manifests files:

    -   Login to server where CE is installed:

        ```
        ssh $USER@$CE_SERVER

        ```

    -   Create new directory:

        ```
        mkdir -p /ce
        cd /ce
        ```

    -   Create `setup.properties` by running the following command:

        ```
        openssl enc -d -aes-256-cbc -in /opt/gluu-server/install/community-edition-setup/setup.properties.last.enc -out setup.properties
        ```

    -   Get all certificates, keys, and keystores:

        ```
        cp /opt/gluu-server/install/community-edition-setup/output/*.crt .
        cp /opt/gluu-server/install/community-edition-setup/output/*.key .
        cp /opt/gluu-server/install/community-edition-setup/output/*.jks .
        cp /opt/gluu-server/install/community-edition-setup/output/*.pkcs12 .
        cp /opt/gluu-server/opt/shibboleth-idp/credentials/*.jks .
        cp /opt/gluu-server/opt/shibboleth-idp/credentials/*.kver .
        cp /opt/gluu-server/etc/certs/*.crt .
        cp /opt/gluu-server/etc/certs/*.key .
        cp /opt/gluu-server/etc/certs/*.jks .
        cp /opt/gluu-server/etc/certs/*.pkcs12 .
        ```

    -   Get `salt` file:

        ```
        cp /opt/gluu-server/etc/gluu/conf/salt .
        ```

    -   Get configuration/secret stored in persistence.
        For LDAP-based persistence, run the following command:

        ```
        opt/opendj/bin/ldapsearch \
            --useSSL \
            --trustAll \
            -D "cn=directory manager" \
            -p 1636 \
            -w $LDAP_PASSWD \
            -b "o=gluu" \
            -s sub '(|(objectClass=oxAuthConfiguration)(objectClass=gluuConfiguration)(objectClass=oxAuthClient))' > backend.ldif
        ```

        Otherwise, for Couchbase-based persistence, run the following N1QL query (in Couchbase UI):

        ```
        SELECT META().id, gluu.dn, gluu.objectClass, gluu.oxAuthConfWebKeys, gluu.oxAuthJwks, oxCacheConfiguration
        FROM gluu
        WHERE objectClass IN  ['oxAuthClient', 'oxAuthConfiguration', 'gluuConfiguration']
        ```

        Save the result as `backend.json` file.

    -   Logout from server where CE is installed

1.  Download manifests files:

    ```
    scp -r $USER@$CE_SERVER:/ce .
    ```

1.  Run the image container:

    ```yaml
    # License terms and conditions for Gluu Cloud Native Edition:
    # https://www.apache.org/licenses/LICENSE-2.0
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: config-init-load-job
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: config-generate-params
              configMap:
                name: config-generate-params
          containers:
            - name: config-init-load
              image: gluufederation/config-init:4.2.3_01
              volumeMounts:
                - mountPath: /opt/config-init/db/generate.json
                  name: config-generate-params
                  subPath: generate.json
              envFrom:
              - configMapRef:
                  name: gluu-config-cm
              args: ["migrate", "--backend", "json"]
    ```

    Note: choose `ldif` if using `backend.ldif` or `json` if using `backend.json` file.

**Comment by iromli** [comment]
The image should be changed to 4.3.0_xx as the feature is applied in 4.3

**Comment by moabu** [comment]
## Updated Steps

1.  Login to the server where CE is installed:

        ssh $USER@$CE_SERVER

1.  Backup the data in persistence and save them elsewhere.

1.  Set an environment variable to mark where the root directory of CE installation is.

    If using chrooted installation:

        export CE_HOME=/opt/gluu-server

    otherwise:

        export CE_HOME=

1.  Prepare manifests files:

    -   Create new directory:

        ```
        mkdir -p $HOME/ce-migration
        cd $HOME/ce-migration
        ```

        Take a note about the full path of this directory (for example `/root/ce-migration`).

    -   Create `setup.properties` by copying `setup.properties.last` (if exists):

            cp $CE_HOME/install/community-edition-setup/setup.properties.last setup.properties

        otherwise:

            openssl enc -d -aes-256-cbc -in $CE_HOME/install/community-edition-setup/setup.properties.last.enc -out setup.properties

    -   Get all certificates, keys, and keystores:

            cp $CE_HOME/etc/certs/*.crt .
            cp $CE_HOME/etc/certs/*.key .
            cp $CE_HOME/etc/certs/*.pem .
            cp $CE_HOME/etc/certs/*.jks .
            cp $CE_HOME/etc/certs/*.pkcs12 .
            cp $CE_HOME/opt/shibboleth-idp/credentials/*.jks .
            cp $CE_HOME/opt/shibboleth-idp/credentials/*.kver .
            cp $CE_HOME/opt/shibboleth-idp/conf/datasource.properties .

    -   Get `salt` file:

            cp $CE_HOME/etc/gluu/conf/salt .

1.  Get configuration/secret stored in persistence.

    -   For LDAP-based persistence, run the following commands:

            $CE_HOME/opt/opendj/bin/ldapsearch \
                --useSSL \
                --trustAll \
                -D "cn=directory manager" \
                -p 1636 \
                -w $LDAP_PASSWD \
                -b "o=gluu" \
                -s sub '(objectClass=gluuConfiguration)' > gluu-configuration.ldif

            $CE_HOME/opt/opendj/bin/ldapsearch \
                --useSSL \
                --trustAll \
                -D "cn=directory manager" \
                -p 1636 \
                -w $LDAP_PASSWD \
                -b "o=gluu" \
                -s sub '(objectClass=oxAuthConfiguration)' > oxauth-configuration.ldif

            $CE_HOME/opt/opendj/bin/ldapsearch \
                --useSSL \
                --trustAll \
                -D "cn=directory manager" \
                -p 1636 \
                -w $LDAP_PASSWD \
                -b "o=gluu" \
                -s sub '(objectClass=oxAuthClient)' > oxauth-client.ldif

        Here's an example of expected `.ldif` file:

            dn: ou=configuration,o=gluu
            gluuHostname: 1b4211097aa4
            gluuOrgProfileMgt: false
            gluuPassportEnabled: false
            gluuRadiusEnabled: false
            gluuSamlEnabled: false
            gluuScimEnabled: false
            gluuVdsCacheRefreshEnabled: true

    -   For Couchbase-based persistence, run the following N1QL queries (in Couchbase UI):

            # save the result as gluu-configuration.json manually
            SELECT META().id, gluu.*
            FROM gluu
            WHERE objectClass = 'gluuConfiguration'

            # save the result as oxauth-configuration.json manually
            SELECT META().id, gluu.*
            FROM gluu
            WHERE objectClass = 'oxAuthConfiguration'

            # save the result as oxauth-client.json manually
            SELECT META().id, gluu.*
            FROM gluu
            WHERE objectClass = 'oxAuthClient'

        Here's an example of the expected `.json` file:

            [
                {
                    "dn": "ou=configuration,o=gluu",
                    "gluuPassportEnabled": false,
                    "gluuRadiusEnabled": false,
                    "gluuSamlEnabled": false,
                    "gluuScimEnabled": false,
                    "gluuVdsCacheRefreshEnabled": false,
                    "id": "configuration",
                    "objectClass": "gluuConfiguration"
                }
            ]

    -   For Spanner-based persistence:

        Follow the official docs at https://cloud.google.com/spanner/docs/export (currently the supported format is Avro only).

        Here's an example of exported Avro filenames:

            gluuConfiguration.avro-00000-of-00001
            oxAuthConfiguration.avro-00000-of-00001
            oxAuthClient.avro-00000-of-00001

        The expected filenames used by config-init container are:

            gluu-configuration.avro
            oxauth-configuration.avro
            oxauth-client.avro

        hence you may need to copy them manually from the original Avro files.

    -   For SQL-based persistence (MySQL dialect):

        Install [mysqlsh](https://dev.mysql.com/doc/mysql-shell/8.0/en/mysql-shell-install.html), then run the following commands:

            echo 'select * from gluuConfiguration' | mysqlsh --json=pretty --sql --show-warnings=false --uri=$DBUSER@$DBHOST:$DBPORT/$DBNAME -p > gluu-configuration.json
            echo 'select * from oxAuthConfiguration' | mysqlsh --json=pretty --sql --show-warnings=false --uri=$DBUSER@$DBHOST:$DBPORT/$DBNAME -p > oxauth-configuration.json
            echo 'select * from oxAuthClient' | mysqlsh --json=pretty --sql --show-warnings=false --uri=$DBUSER@$DBHOST:$DBPORT/$DBNAME -p > oxauth-client.json

        Here's an example of the expected `.json` file:

            {
                "hasData": true,
                "rows": [
                    {
                        "doc_id": "configuration",
                        "objectClass": "gluuConfiguration",
                        "dn": "ou=configuration,o=gluu",
                        "description": null,
                        "oxSmtpConfiguration": {
                            "v": []
                        },
                        "gluuVDSenabled": null,
                        "ou": "configuration",
                        "gluuStatus": null,
                        "displayName": null
                    }
                ]
            }

    -   For SQL-based persistence (PostgreSQL dialect):

            psql -h $DBHOST -p $DBPORT -U $DBUSER -d $DBNAME -W -t -A -o gluu-configuration.json -c 'select json_agg(t) from (select * from "gluuConfiguration") t;'
            psql -h $DBHOST -p $DBPORT -U $DBUSER -d $DBNAME -W -t -A -o oxauth-configuration.json -c 'select json_agg(t) from (select * from "oxAuthConfiguration") t;'
            psql -h $DBHOST -p $DBPORT -U $DBUSER -d $DBNAME -W -t -A -o oxauth-client.json -c 'select json_agg(t) from (select * from "oxAuthClient") t;'

        Here's an example of the expected `.json` file:

            [
                {
                    "doc_id": "configuration",
                    "objectClass": "gluuConfiguration",
                    "dn": "ou=configuration,o=gluu",
                    "oxTrustStoreConf": "{\"useJreCertificates\":true}",
                    "gluuAdditionalMemory": null,
                    "gluuSmtpRequiresAuthentication": null,
                    "gluuPassportEnabled": 0,
                    "gluuShibFailedAuth": null,
                    "gluuAppliancePollingInterval": null,
                    "gluuAdditionalBandwidth": null,
                    "gluuRadiusEnabled": 0,
                    "description": null
                }
            ]

1.  Logout from the server where CE is installed.

1.  Download manifests files:

        scp -r $USER@$CE_SERVER:/root/ce-migration .

1.  Run the container to migrate CE configuration to CN configuration:

    ```yaml
    # License terms and conditions for Gluu Cloud Native Edition:
    # https://www.apache.org/licenses/LICENSE-2.0
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: config-init-load-job
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: config-generate-params
              configMap:
                name: config-generate-params
          containers:
            - name: config-init-load
              image: gluufederation/config-init:4.3.0_dev
              volumeMounts:
                - mountPath: /opt/config-init/db/generate.json
                  name: config-generate-params
                  subPath: generate.json
              envFrom:
              - configMapRef:
                  name: gluu-config-cm
              args: ["migrate", "--backend", "json"]
    ```

    Supported data format:

    - `ldif`
    - `couchbase+json`
    - `spanner+avro`
    - `postgresql+json`
    - `mysql+json`

1.  Import backup data into persistence manually.

1.  Deploy oxAuth, oxTrust, and nginx/ingress services and verify whether migration with basic deployment worked.

1.  If additional services are required (i.e. SCIM, Fido2, etc), run container/k8s job of `gluufederation/persistence` image to fill the missing entries (existing entries will not be modified). Note that some configuration may need to be modified manually via oxTrust UI.

1.  Deploy additional services and verify whether migration is working as expected.
