### ISSUE TITLE
Port configuration is not applied properly

### ISSUE THREAD

**Issue by mookkiah** [GluuFederation/cloud-native-edition#279]
We have given input for the port related question as below
```
Standard Port/Protocol, Gluu standard Node Port -- PURPOSE -- OUR PORT
4444/TCP,30444 -- ADVERTISE_ADMIN_PORT -- 32742
1389/TCP, NA -- LDAP_PORT (unsecure)
1636/TCP,30636 -- LDAPS_PORT -- 32743
8989/TCP,30989 -- REPLICATION_PORT -- 32744
7946/TCP,30946 -- SERF_PORT -- 32745
7946/UDP,30946 -- SERF_PORT – 32745
```
Which resulted setting.json as below

```
  "GLUU_LDAP_MULTI_CLUSTER": "Y",
  "GLUU_LDAP_SERF_PORT": "32745",
  "GLUU_LDAP_ADVERTISE_ADDRESS": "firstldab.example.com:32745",
  "GLUU_LDAP_ADVERTISE_ADMIN_PORT": "32742",
  "GLUU_LDAP_ADVERTISE_LDAPS_PORT": "32743",
  "GLUU_LDAP_ADVERTISE_REPLICATION_PORT": "32744",
  "GLUU_LDAP_SECONDARY_CLUSTER": "N",
  "GLUU_LDAP_SERF_PEERS": "['firstldab.example.com','secondldap.example.com']"
```

This generates values.yaml for gluu as below

opendj -- Not sure why tcp-repl and tcp-admin container port took high numbers. I am expecting to have 4444 
```
  ports:
    tcp-ldaps:
      port: 1636
      targetPort: 1636
      protocol: TCP
      nodePort: 32743
    tcp-ldap:
      port: 1389
      targetPort: 1389
      protocol: TCP
      nodePort: ""
    tcp-repl:
      port: 32744
      targetPort: 32744
      protocol: TCP
      nodePort: 32744
    tcp-admin:
      port: 32742
      targetPort: 32742
      protocol: TCP
      nodePort: 32742
    tcp-serf:
      port: 7946
      targetPort: 7946
      protocol: TCP
      nodePort: 32745
    udp-serf:
      port: 7946
      targetPort: 7946
      protocol: UDP
      nodePort: 32745
```

Even if that is right.... the cronjob configuration is expecting the default port 4444. I believe either one is wrong

```
    Command:
      /bin/sh
      -c
      /app/scripts/entrypoint.sh &
      sleep 300
      RANDOM_NUM=$(cat /dev/urandom | tr -cd '0-5' | head -c 1)
      LDAP_BACKUP_FILE=backup-$RANDOM_NUM.ldif
      /opt/opendj/bin/export-ldif --hostname "$LDAP_HOST" --port 4444 --bindDN "$LDAP_BIND_DN" --bindPassword "$LDAP_PASSWORD" --backendID userRoot --ldifFile /opt/opendj/ldif/$LDAP_BACKUP_FILE --trustAll
      
```

AFAIK either [this line](https://github.com/GluuFederation/cloud-native-edition/blob/master/pygluu/kubernetes/templates/helm/ldap-backup/templates/cronjobs.yaml#L55) needs change or [this line](https://github.com/GluuFederation/cloud-native-edition/blob/master/pygluu/kubernetes/gluu.py#L308) and [this line](https://github.com/GluuFederation/cloud-native-edition/blob/master/pygluu/kubernetes/gluu.py#L315) should be removed.
