### ISSUE TITLE
LDAP backup pods missing /etc/gluu/conf/serf-peers-static.json

### ISSUE THREAD

**Issue by mookkiah** [GluuFederation/cloud-native-edition#280]
LDAP backup pods are throwing error as below...

```
INFO - ldap_peer - 2021-01-18 13:07:39,154 - Loading initial Serf peers from /etc/gluu/conf/serf-peers-static.json
WARNING - ldap_peer - 2021-01-18 13:07:39,154 - Unable to load initial Serf peers from /etc/gluu/conf/serf-peers-static.json; reason=[Errno 2] No such file or directory: '/etc/gluu/conf/serf-peers-static.json'

```

After discussing with @moabu, we believe the volume and volume mounts should be added in the [cronjob](https://github.com/GluuFederation/cloud-native-edition/blob/master/pygluu/kubernetes/templates/helm/ldap-backup/templates/cronjobs.yaml) template spec
```
        - mountPath: /etc/gluu/conf/serf-peers-static.json
          name: serfpeers
          subPath: serf-peers-static.json

      - configMap:
          defaultMode: 420
          name: gluu-serf-peers
        name: serfpeers
```
