### ISSUE TITLE
Jackrabbit admin password always admin instead of configured value.

### ISSUE THREAD

**Issue by mookkiah** [GluuFederation/cloud-native-edition#282]
**Describe the bug**
pygluu helm install not using jackrabbit passwords

**Additional context**
I think it is a bug in helm chart development 
In [this line](https://github.com/GluuFederation/cloud-native-edition/blob/5ee9a4194d99976aa39350a20e4c263023405ba1/pygluu/kubernetes/templates/helm/gluu/charts/jackrabbit/templates/secret.yaml#L10) the jackrabbit chart takes password from `.Values.secrets.cnJackrabbitAdminPass` and it is given [properly in values.yaml](https://github.com/GluuFederation/cloud-native-edition/blob/5ee9a4194d99976aa39350a20e4c263023405ba1/pygluu/kubernetes/templates/helm/gluu/values.yaml#L151)

But when generating values.yaml from settings.json it ends up in `gluuJackrabbitAdminPass`

```
jackrabbit:
  service:
    jackRabbitServiceName: jackrabbit
  replicas: 1
  secrets:
    gluuJackrabbitAdminPass: c@[,,=]~L70[D%bpkbj^d.Mv
    gluuJackrabbitPostgresPass: ''
  storage:
    size: 5Gi
  image:
    repository: gluufederation/jackrabbit
    tag: 4.2.2_02
    pullPolicy: Always
  resources:
    limits:
      cpu: 1500m
      memory: 1000Mi
    requests:
      cpu: 1500m
      memory: 1000Mi
```

This is because of this line - https://github.com/GluuFederation/cloud-native-edition/blob/v1.3.2/pygluu/kubernetes/helm.py#L301
