### ISSUE TITLE
Add FAPI configuration

### ISSUE THREAD

**Issue by moabu** [GluuFederation/cloud-native-edition#320]
- [ ]  Create option for setting fapiCompatibility to true in Jans authorization server Application configuration properties

- [ ]  Add ingress definitions. The following is waiting on RP development of the serverlets as it should not be coupled with the AS.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: gluu
    meta.helm.sh/release-namespace: gluu
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    nginx.ingress.kubernetes.io/auth-tls-secret: gluu/tls-ob-ca-certificates
    nginx.ingress.kubernetes.io/auth-tls-verify-client: optional
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/proxy-next-upstream: error timeout invalid_header
      http_500 http_502 http_503 http_504
    nginx.org/ssl-services: auth-server
    nginx.ingress.kubernetes.io/configuration-snippet: "rewrite /open-banking/v3.1/aisp/account-access-consents /jans-auth/open-banking/v3.1/aisp/account-access-consents$1 break;"
    nginx.ingress.kubernetes.io/rewrite-target: /jans-auth/open-banking/v3.1/aisp/account-access-consents
    nginx.ingress.kubernetes.io/configuration-snippet: |
	    if ($ssl_client_verify != SUCCESS) {return 400;}
	    proxy_set_header X-ClientCert $ssl_client_escaped_cert;
  labels:
    app: auth-server
    app.kubernetes.io/managed-by: Helm
  name: gluu-nginx-ingress-openbanking-account-access-consents
  namespace: gluu
spec:
  rules:
  - host: bank.testingluuk8.org
    http:
      paths:
      - backend:
	  serviceName: auth-server
	  servicePort: 8080
	path: /open-banking/v3.1/aisp/account-access-consents
	pathType: Exact
  tls:
  - hosts:
    - bank.testingluuk8.org
    secretName: tls-cert-manager-certificate
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: gluu
    meta.helm.sh/release-namespace: gluu
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    nginx.ingress.kubernetes.io/auth-tls-secret: gluu/tls-ob-ca-certificates
    nginx.ingress.kubernetes.io/auth-tls-verify-client: optional
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/proxy-next-upstream: error timeout invalid_header
      http_500 http_502 http_503 http_504
    nginx.org/ssl-services: auth-server
    nginx.ingress.kubernetes.io/configuration-snippet: "rewrite /open-banking/v3.1/aisp/accounts /jans-auth/open-banking/v3.1/aisp/accounts$1 break;"
    nginx.ingress.kubernetes.io/rewrite-target: /jans-auth/open-banking/v3.1/aisp/accounts
    nginx.ingress.kubernetes.io/configuration-snippet: |
	    if ($ssl_client_verify != SUCCESS) {return 400;}
	    proxy_set_header X-ClientCert $ssl_client_escaped_cert;
  labels:
    app: auth-server
    app.kubernetes.io/managed-by: Helm
  name: gluu-nginx-ingress-openbanking-accounts
  namespace: gluu
spec:
  rules:
  - host: bank.testingluuk8.org
    http:
      paths:
      - backend:
	  serviceName: auth-server
	  servicePort: 8080
	path: /open-banking/v3.1/aisp/accounts
	pathType: Exact
  tls:
  - hosts:
    - bank.testingluuk8.org
    secretName: tls-cert-manager-certificate
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: gluu
    meta.helm.sh/release-namespace: gluu
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    nginx.ingress.kubernetes.io/auth-tls-secret: gluu/tls-ob-ca-certificates
    nginx.ingress.kubernetes.io/auth-tls-verify-client: optional
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/proxy-next-upstream: error timeout invalid_header
      http_500 http_502 http_503 http_504
    nginx.org/ssl-services: auth-server
    nginx.ingress.kubernetes.io/configuration-snippet: "rewrite /open-banking/v3.1/aisp /jans-auth/open-banking/v3.1/aisp$1 break;"
    nginx.ingress.kubernetes.io/rewrite-target: /jans-auth/open-banking/v3.1/aisp
    nginx.ingress.kubernetes.io/configuration-snippet: |
	    if ($ssl_client_verify != SUCCESS) {return 400;}
	    proxy_set_header X-ClientCert $ssl_client_escaped_cert;
  labels:
    app: auth-server
    app.kubernetes.io/managed-by: Helm
  name: gluu-nginx-ingress-openbanking-aisp
  namespace: gluu
spec:
  rules:
  - host: bank.testingluuk8.org
    http:
      paths:
      - backend:
	  serviceName: auth-server
	  servicePort: 8080
	path: /open-banking/v3.1/aisp
	pathType: Exact
  tls:
  - hosts:
    - bank.testingluuk8.org
    secretName: tls-cert-manager-certificate
```

- [ ] Set only allowed ciphers in ingress-nginx controller

```yaml
nginx.ingress.kubernetes.io/ssl-ciphers: ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256
```
