### ISSUE TITLE
Set Session cookie attributes on ingress

### ISSUE THREAD

**Issue by moabu** [GluuFederation/cloud-native-edition#341]
**Is your feature request related to a problem? Please describe.**
The ingress definitions shows that the Session ID cookie does not set the following attributes:

HttpOnly: This attribute is used to help prevent attacks such as cross-site scripting, since it does not allow the cookie to be accessed via a client side script such as JavaScript.

SameSite: prevents the browser from sending this cookie along with cross-site requests. The main goal is mitigate the risk of cross-origin information leakage. It also provides some protection against cross-site request forgery attacks.

Domain: should be set to the origin host to limit the scope to that particular server. For example if the application resides on server app.mysite.com, then it should be set to domain=app.mysite.com

**Describe the solution you'd like**

annotationns
To respond to above:

 > HttpOnly: This attribute is used to help prevent attacks such as cross-site scripting, since it does not allow the cookie to be accessed via a client side script such as JavaScript.
 > 

add annotation :

`nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Set-Cookie: HttpOnly";`

 > SameSite: prevents the browser from sending this cookie along with cross-site requests. The main goal is mitigate the risk of cross-origin information leakage. It also provides some protection against cross-site request forgery attacks.
 > 

add ingress annotation `nginx.ingress.kubernetes.io/session-cookie-samesite: "app.mysite.com"`

"Browser accepted values are None, Lax, and Strict. Some browsers reject cookies with SameSite=None, including those created before the SameSite=None specification (e.g. Chrome 5X). Other browsers mistakenly treat SameSite=None cookies as SameSite=Strict (e.g. Safari running on OSX 14). To omit SameSite=None from browsers with these incompatibilities, add the annotation nginx.ingress.kubernetes.io/session-cookie-conditional-samesite-none: "true"."

> Domain: should be set to the origin host to limit the scope to that particular server. For example if the application resides on server app.mysite.com, then it should be set to domain=app.mysite.com
> 

add ingress annotation `nginx.ingress.kubernetes.io/proxy-cookie-domain: "app.mysite.com"`

helm changes:

```yaml
    nginx.ingress.kubernetes.io/configuration-snippet: 'more_set_headers "Set-Cookie: HttpOnly";'
    nginx.ingress.kubernetes.io/session-cookie-samesite: {{ .Values.global.domain | quote }}
    nginx.ingress.kubernetes.io/proxy-cookie-domain: {{ .Values.global.domain | quote }}
```
