### ISSUE TITLE
support exporting several application logs to STDOUT

### ISSUE THREAD

**Issue by moabu** [GluuFederation/cloud-native-edition#395]
Target branch: `4.3`

Add configuration for supporting passing in the following envs: 

### oxtrust

```
GLUU_OXTRUST_APP_LOGGERS={
     "oxtrust_log_target": "STDOUT",
     "oxtrust_log_level": "INFO",
     "http_log_target": "FILE",
     "http_log_level": "INFO",
     "persistence_log_target": "FILE",
     "persistence_log_level": "INFO",
     "persistence_duration_log_target": "FILE",
     "persistence_duration_log_level": "INFO",
     "ldap_stats_log_target": "FILE",
     "ldap_stats_log_level": "INFO",
     "script_log_target": "FILE",
     "script_log_level": "INFO",
     "audit_log_target": "FILE",
     "audit_log_level": "INFO",
     "cleaner_log_target": "FILE"
     "cleaner_log_level": "INFO",
     "velocity_log_target": "FILE"
     "velocity_log_level": "INFO",
     "cache_refresh_log_target": "FILE"
     "cache_refresh_log_level": "INFO",
     "cache_refresh_python_log_target": "FILE"
     "cache_refresh_python_log_level": "INFO",
     "apachehc_log_target": "FILE",
     "apachehc_log_level": "OFF"
 }
```

### oxauth

```
GLUU_OXAUTH_APP_LOGGERS={
     "oxauth_log_target": "STDOUT",
     "oxauth_log_level": "INFO",
     "http_log_target": "FILE",
     "http_log_level": "INFO",
     "persistence_log_target": "FILE",
     "persistence_log_level": "INFO",
     "persistence_duration_log_target": "FILE",
     "persistence_duration_log_level": "INFO",
     "ldap_stats_log_target": "FILE",
     "ldap_stats_log_level": "INFO",
     "script_log_target": "FILE",
     "script_log_level": "INFO",
     "audit_log_target": "FILE",
     "audit_log_level": "INFO",
     "cleaner_log_level": "INFO",
     "cleaner_log_target": "FILE"
 }
```

### SCIM

```
GLUU_SCIM_APP_LOGGERS={
    "scim_log_target": "STDOUT",
    "scim_log_level": "INFO",
    "persistence_log_target": "FILE",
    "persistence_log_level": "INFO",
    "persistence_duration_log_target": "FILE",
    "persistence_duration_log_level": "INFO",
    "ldap_stats_log_target": "FILE",
    "ldap_stats_log_level": "INFO",
    "script_log_target": "FILE",
    "script_log_level": "INFO",
}

```

### FIDO2

```
GLUU_FIDO2_APP_LOGGERS={
     "fido2_log_target": "STDOUT",
     "fido2_log_level": "INFO",
     "persistence_log_target": "FILE",
     "persistence_log_level": "INFO"
 }

```

### OXSHIBBOLETH

```
CN_OXSHIBBOELTH_APP_LOGGERS={
     "idp_log_target": "STDOUT",
     "idp_log_level": "INFO",
     "script_log_target": "FILE",
     "script_log_level": "INFO",
     "audit_log_target": "FILE",
     "audit_log_level": "INFO",
     "consent_audit_log_target": "FILE",
     "consent_audit_log_level": "INFO",
 }

```

### OXD SERVER

```
GLUU_OXD_SERVER_APP_LOGGERS={
     "oxd_log_target": "STDOUT",
     "oxd_log_level": "INFO"
 }
```

App loggers can be configured to define where the logs will be redirected and what is the level the logs should be displayed.

Supported redirect target:

- `STDOUT`
- `FILE`

Supported level:

- `FATAL`
- `ERROR`
- `WARN`
- `INFO`
- `DEBUG`
- `TRACE`

**Comment by moabu** [comment]
user will be able to control logs by using the following key-value pairs in `values.yaml` : 

```yaml
# -- Parameters used globally across all services helm charts.
global:
  oxauth:
    # -- Boolean flag to enable/disable oxauth chart. You should never set this to false.
    enabled: true
    # -- App loggers can be configured to define where the logs will be redirected to and the level of each in which it should be displayed.
    # log levels are "OFF", "FATAL", "ERROR", "WARN", "INFO", "DEBUG", "TRACE"
    # Targets are "STDOUT" and "FILE"
    appLoggers:
      # -- oxauth.log target
      authLogTarget: "STDOUT"
      # -- oxauth.log level
      authLogLevel: "INFO"
      # -- http_request_response.log target
      httpLogTarget: "FILE"
      # -- http_request_response.log level
      httpLogLevel: "INFO"
      # -- oxauth_persistence.log target
      persistenceLogTarget: "FILE"
      # -- oxauth_persistence.log level
      persistenceLogLevel: "INFO"
      # -- oxauth_persistence_duration.log target
      persistenceDurationLogTarget: "FILE"
      # -- oxauth_persistence_duration.log level
      persistenceDurationLogLevel: "INFO"
      # -- oxauth_persistence_ldap_statistics.log target
      ldapStatsLogTarget: "FILE"
      # -- oxauth_persistence_ldap_statistics.log level
      ldapStatsLogLevel: "INFO"
      # -- oxauth_script.log target
      scriptLogTarget: "FILE"
      # -- oxauth_script.log level
      scriptLogLevel: "INFO"
      # -- oxauth_script.log target
      auditStatsLogTarget: "FILE"
      # -- oxauth_audit.log level
      auditStatsLogLevel: "INFO"
      # -- cleaner log target
      cleanerLogTarget: "FILE"
      # -- cleaner log level
      cleanerLogLevel: "INFO"
  fido2:
    # -- Boolean flag to enable/disable the fido2 chart.
    enabled: false
    # -- App loggers can be configured to define where the logs will be redirected to and the level of each in which it should be displayed.
    # log levels are "OFF", "FATAL", "ERROR", "WARN", "INFO", "DEBUG", "TRACE"
    # Targets are "STDOUT" and "FILE"
    appLoggers:
      # -- fido2.log target
      fido2LogTarget: "STDOUT"
      # -- fido2.log level
      fido2LogLevel: "INFO"
      # -- fido2_persistence.log target
      persistenceLogTarget: "FILE"
      # -- fido2_persistence.log level
      persistenceLogLevel: "INFO"
  scim:
    # -- Boolean flag to enable/disable the SCIM chart.
    enabled: false
    # -- App loggers can be configured to define where the logs will be redirected to and the level of each in which it should be displayed.
    # log levels are "OFF", "FATAL", "ERROR", "WARN", "INFO", "DEBUG", "TRACE"
    # Targets are "STDOUT" and "FILE"
    appLoggers:
      # -- scim.log target
      scimLogTarget: "STDOUT"
      # -- scim.log level
      scimLogLevel: "INFO"
      # -- scim_persistence.log target
      persistenceLogTarget: "FILE"
      # -- scim_persistence.log level
      persistenceLogLevel: "INFO"
      # -- scim_persistence_duration.log target
      persistenceDurationLogTarget: "FILE"
      # -- scim_persistence_duration.log level
      persistenceDurationLogLevel: "INFO"
      # -- scim_script.log target
      scriptLogTarget: "FILE"
      # -- scim_script.log level
      scriptLogLevel: "INFO"
  oxtrust:
    # -- Boolean flag to enable/disable the oxtrust chart.
    enabled: true
    # -- App loggers can be configured to define where the logs will be redirected to and the level of each in which it should be displayed.
    # log levels are "OFF", "FATAL", "ERROR", "WARN", "INFO", "DEBUG", "TRACE"
    # Targets are "STDOUT" and "FILE"
    appLoggers:
      # -- oxtrust.log target
      oxtrustLogTarget: "STDOUT"
      # -- oxtrust.log level
      oxtrustLogLevel: "INFO"
      # -- http_request_response.log target
      httpLogTarget: "FILE"
      # -- http_request_response.log level
      httpLogLevel: "INFO"
      # -- oxtrust_persistence.log target
      persistenceLogTarget: "FILE"
      # -- oxtrust_persistence.log level
      persistenceLogLevel: "INFO"
      # -- oxtrust_persistence_duration.log target
      persistenceDurationLogTarget: "FILE"
      # -- oxtrust_persistence_duration.log level
      persistenceDurationLogLevel: "INFO"
      # -- oxtrust_persistence_ldap_statistics.log target
      ldapStatsLogTarget: "FILE"
      # -- oxtrust_persistence_ldap_statistics.log level
      ldapStatsLogLevel: "INFO"
      # -- oxtrust_script.log target
      scriptLogTarget: "FILE"
      # -- oxtrust_script.log level
      scriptLogLevel: "INFO"
      # -- oxtrust_script.log target
      auditStatsLogTarget: "FILE"
      # -- oxtrust_audit.log level
      auditStatsLogLevel: "INFO"
      # -- cleaner log target
      cleanerLogTarget: "FILE"
      # -- cleaner log target
      cleanerLogLevel: "INFO"
      # -- velocity log level
      velocityLogLevel: "INFO"
      # -- velocity log target
      velocityLogTarget: "FILE"
      # -- cache refresh log level
      cacheRefreshLogLevel: "INFO"
      # -- cache refresh log target
      cacheRefreshLogTarget: "FILE"
      # -- cleaner log level
      cacheRefreshPythonLogLevel: "INFO"
      # -- cache refresh python log target
      cacheRefreshPythonLogTarget: "FILE"
      # -- apachehc log level
      apachehcLogLevel: "INFO"
      # -- apachehc log target
      apachehcLogTarget: "FILE"
  oxshibboleth:
    # -- Boolean flag to enable/disable the oxShibbboleth chart.
    enabled: false
    # -- App loggers can be configured to define where the logs will be redirected to and the level of each in which it should be displayed.
    # log levels are "OFF", "FATAL", "ERROR", "WARN", "INFO", "DEBUG", "TRACE"
    # Targets are "STDOUT" and "FILE"
    appLoggers:
      # -- idp-process.log target
      idpLogTarget: "STDOUT"
      # -- idp-process.log level
      idpLogLevel: "INFO"
      # -- idp script.log target
      scriptLogTarget: "FILE"
      # -- idp script.log level
      scriptLogLevel: "INFO"
      # -- idp-audit.log target
      auditStatsLogTarget: "FILE"
      # -- idp-audit.log level
      auditStatsLogLevel: "INFO"
      # -- idp-consent-audit.log target
      consentAuditLogTarget: "FILE"
      # -- idp-consent-audit.log level
      consentAuditLogLevel: "INFO"

  oxd-server:
    # -- Boolean flag to enable/disable the oxd-server chart.
    enabled: false
    # -- App loggers can be configured to define where the logs will be redirected to and the level of each in which it should be displayed.
    # log levels are "OFF", "FATAL", "ERROR", "WARN", "INFO", "DEBUG", "TRACE"
    # Targets are "STDOUT" and "FILE"
    appLoggers:
      # -- oxd-server.log target
      oxdServerLogTarget: "STDOUT"
      # -- oxd-server.log level
      oxdServerLogLevel: "INFO"
```
