### ISSUE TITLE
fix(istio): accessing /casa return 404 status code

### ISSUE THREAD

**Issue by iromli** [GluuFederation/cloud-native-edition#473]
**Describe the bug**

When using Istio gateway, accessing `/casa` always returns 404 status code.

**To Reproduce**
1. Deploy Gluu with Istio (make sure Casa service is enabled during install prompt)
2. Make request to `/casa`
3. See 404 status code

**Expected behavior**

Accessing `/casa` returns non 404 status code.

**Comment by iromli** [comment]
@moabu these lines rejects the request:

```
http:
  - name: {{ .Release.Name }}-istio-casa
    match:
    - uri:
        exact: /casa
```

I think it should be `prefix` instead of `exact`.
