### ISSUE TITLE
fix(istio): accessing /idp return 404 status code

### ISSUE THREAD

**Issue by iromli** [GluuFederation/cloud-native-edition#474]
**Describe the bug**

When using Istio gateway, accessing `/idp` (shibboleth) always returns 404 status code. Further inspection shows that `/idp` is rewritten to `/identity`.

**To Reproduce**
1. Deploy Gluu with Istio (make sure Shibboleth service is enabled during install prompt)
2. Make request to `/idp/shibboleth`
3. See 404 status code

**Expected behavior**

Accessing `/idp/shibboleth` returns non 404 status code.

**Comment by iromli** [comment]
@moabu 

```
http:
  - name: {{ .Release.Name }}-istio-oxshibbioleth
    match:
    - uri:
        prefix: /idp
    rewrite:
      uri: /identity
```

Either `rewrite` to `/idp` or remove the `rewrite` would fix the issue.
