### ISSUE TITLE
fix: label selector for scim and auth-server ineffictive

### ISSUE THREAD

**Issue by moabu** [GluuFederation/cloud-native-edition#564]
gluu's helm chart allows to enable pod topology spread constraints. But the label selector contains an error. Seen in oxauth and scim:
```
# snippet from scim deployment
topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: dev-gluu-oxauth
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
```

The label selector is created by the helm chart template. It should be "app: scim" and "app: oxauth".
Currently, the constraint has no effect.
